### ISSUE TITLE
restyling of edit links page

### ISSUE THREAD

**Issue by giuseppe2028** [giacomoponzuoli3/KirunaExplorer#9]
The edit links page if a little bit confusing, is better to redesign it. For instance eliminating green and red colors, because these colors usually mean correct and wrong.

**Comment by giacomoponzuoli3** [comment]
I took into account the feedback regarding the use of the colors green and red, which can be associated with the concepts of right and wrong. To avoid confusion, I removed these colors and chose a more neutral and professional combination.

I used blue to emphasize the titles of the documents, in order to maintain a consistent and visually pleasing look. Also, for the link type part, I opted for a dark blue shade for the link name, maintaining enough contrast without being too strong. I also added spaces and improved the readability of the content, to make the page clearer and easier to understand.
